In [2]:
from bo_icp.bo_icp import BayesICP
import bo_icp.utils as icp_utils
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
config_path = '../config/config_c.yaml'
source = "KITTI/sequences/00/pcd/001100.pcd"
target = "KITTI/sequences/00/pcd/001102.pcd"
bayes_icp = BayesICP(config = config_path, source_cloud=source, target_cloud=target, format="KITTI")


In [4]:
bayes_icp.run_bayes_opt_icp()


{'roll': [-3.1416, 3.1416], 'pitch': [-3.1416, 3.1416], 'yaw': [-3.1416, 3.1416]}
|   iter    |  target   |   pitch   |   roll    |    yaw    |
-------------------------------------------------------------
|  1        | -11.0     | -0.5214   |  1.384    | -3.141    |
|  2        | -19.14    | -1.242    | -2.22     | -2.561    |
|  3        | -17.83    | -1.971    | -0.9704   | -0.6486   |
|  4        | -9.376    |  0.2439   | -0.5077   |  1.164    |
|  5        | -19.29    | -1.857    |  2.376    | -2.97     |
|  6        | -16.93    |  1.071    | -0.5196   |  0.3688   |
|  7        | -16.13    | -2.26     | -1.897    |  1.89     |
|  8        | -10.75    |  2.942    | -1.172    |  1.208    |
|  9        | -13.74    |  2.365    |  2.479    | -2.607    |
|  10       | -10.73    | -2.896    | -2.075    |  2.376    |
|  11       | -11.55    | -2.524    | -0.4957   |  2.877    |
|  12       | -13.29    |  0.2084   |  1.206    | -1.159    |
|  13       | -18.68    |  1.172    |  2.103    | 

In [25]:
print(bayes_icp.run_time)

41.51642155647278


In [5]:
icp_utils.draw_icp_result(bayes_icp.source_cloud_viz, bayes_icp.target_cloud_viz, bayes_icp.optimal_transform)

In [21]:
print(bayes_icp.optimal_param)

{'pitch': 3.1416, 'roll': -3.1416, 'yaw': 3.1416, 'x': 0.016775581824682913, 'y': -0.03371636803597344, 'z': 0.004813877395934412}


In [8]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.5f}".format(x)})
print(bayes_icp.optimal_transform)
test_tf = [[0.04120224210927171, -0.20606114354107444, -0.9776713048707698, 0.0], [-0.3896376300023283, 0.8977186016799886, -0.20563032238435716, 0.0], [0.9200461360884777, 0.3894099604790184, -0.04330115643249808, 0.0], [0.0, 0.0, 0.0, 1.0]]


[[1.00000 -0.00001 -0.00001 2.52011]
 [0.00001 1.00000 0.00001 0.16655]
 [0.00001 -0.00001 1.00000 0.01576]
 [0.00000 0.00000 0.00000 1.00000]]


In [9]:
bayes_icp.evalute_icp(bayes_icp.optimal_transform, metric='distance')

0.43429713998712466

In [10]:
print([list(i) for i in bayes_icp.optimal_transform])

[[0.9999999999460303, -7.346410206445345e-06, -7.346410206643587e-06, 2.520113729838923], [7.346464176188268e-06, 0.9999999999460298, 7.346410206445345e-06, 0.166549239744334], [7.346356236504178e-06, -7.346464176188268e-06, 0.9999999999460303, 0.01576375612582792], [0.0, 0.0, 0.0, 1.0]]
